language: java

jdk:
  - oraclejdk11
  - openjdk11

dist: trusty

before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.6.2/binaries/apache-maven-3.6.2-bin.zip
  - unzip -qq apache-maven-3.6.2-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.6.2
  - export PATH=$M2_HOME/bin:$PATH
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install: true

script:
  - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
  - mvn --errors clean verify site
  - bash <(curl -s https://codecov.io/bash) -f ./com.io7m.jwheatsheaf.tests/target/site/jacoco-aggregate/jacoco.xml

notifications:
  irc: "chat.freenode.net#io7m"

